meta_product_name: "Where I Work"

meta_title: "Where I Work â€“ Where I work, you can too!"

meta_description: "Find your next best cafe work place experience!"

meta_image: "wiw.png" # should exist in `app/assets/images/`
